const ORDER_STATUSES = {
  PLACED: 'PLACED',
  AWAITING_STORE_ACCEPTANCE: 'AWAITING_STORE_ACCEPTANCE',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  OTP_VERIFIED: 'OTP_VERIFIED',
  PICKED_UP: 'PICKED_UP',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  RETURN_REQUESTED: 'RETURN_REQUESTED',
  RETURN_ACCEPTED: 'RETURN_ACCEPTED',
  RETURN_REJECTED: 'RETURN_REJECTED',
  RETURN_VERIFICATION_PENDING: 'RETURN_VERIFICATION_PENDING',
  RETURN_VERIFIED_PASS: 'RETURN_VERIFIED_PASS',
  RETURN_VERIFIED_FAIL: 'RETURN_VERIFIED_FAIL',
  RETURN_COMPLETED: 'RETURN_COMPLETED',
  RETURN_CANCELLED: 'RETURN_CANCELLED',
};

const VALID_TRANSITIONS = {
  [ORDER_STATUSES.PLACED]: [ORDER_STATUSES.AWAITING_STORE_ACCEPTANCE, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.AWAITING_STORE_ACCEPTANCE]: [ORDER_STATUSES.ACCEPTED, ORDER_STATUSES.REJECTED, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.ACCEPTED]: [ORDER_STATUSES.READY_FOR_PICKUP, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.REJECTED]: [],
  [ORDER_STATUSES.READY_FOR_PICKUP]: [ORDER_STATUSES.OTP_VERIFIED, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.OTP_VERIFIED]: [ORDER_STATUSES.PICKED_UP],
  [ORDER_STATUSES.PICKED_UP]: [ORDER_STATUSES.COMPLETED],
  [ORDER_STATUSES.COMPLETED]: [ORDER_STATUSES.RETURN_REQUESTED],
  [ORDER_STATUSES.CANCELLED]: [],
  [ORDER_STATUSES.RETURN_REQUESTED]: [ORDER_STATUSES.RETURN_ACCEPTED, ORDER_STATUSES.RETURN_REJECTED],
  [ORDER_STATUSES.RETURN_ACCEPTED]: [ORDER_STATUSES.RETURN_VERIFICATION_PENDING],
  [ORDER_STATUSES.RETURN_REJECTED]: [],
  [ORDER_STATUSES.RETURN_VERIFICATION_PENDING]: [ORDER_STATUSES.RETURN_VERIFIED_PASS, ORDER_STATUSES.RETURN_VERIFIED_FAIL],
  [ORDER_STATUSES.RETURN_VERIFIED_PASS]: [ORDER_STATUSES.RETURN_COMPLETED],
  [ORDER_STATUSES.RETURN_VERIFIED_FAIL]: [ORDER_STATUSES.RETURN_CANCELLED],
  [ORDER_STATUSES.RETURN_COMPLETED]: [ORDER_STATUSES.RETURN_CANCELLED],
  [ORDER_STATUSES.RETURN_CANCELLED]: [],
};

function isValidTransition(from, to) {
  return (VALID_TRANSITIONS[from] || []).includes(to);
}

module.exports = { ORDER_STATUSES, VALID_TRANSITIONS, isValidTransition };
